name: Java CI with Maven and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.2
        options: --privileged

    env:
      DB_HOST: 127.0.0.1
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASS: test_pass

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Compose
        run: |
          docker-compose up -d mysqlDb

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            docker exec $(docker ps -qf "ancestor=mysql:8.3") mysqladmin ping -h"localhost" -u"$DB_USER" -p"$DB_PASS" --silent && break
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean install
