name: Java CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Copy CI environment variables
        run: cp .env.ci .env  # make sure .env.ci is committed or adjust if you use .env directly

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL..."
          until docker exec $(docker ps -qf "name=backend") sh -c 'echo > /dev/tcp/$DB_HOST/3306'; do
            sleep 2
          done
          echo "✅ MySQL is ready"

      - name: Run Maven tests in backend container
        run: |
          docker exec $(docker ps -qf "name=backend") mvn test

      - name: Shut down containers
        run: docker-compose down
